// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoev2Ah_GURyHX5vQPXUBK_JGvWf3ZaHE',
    appId: '1:510454324226:web:6d36462354ddbb21fddb1b',
    messagingSenderId: '510454324226',
    projectId: 'resume-builder-7dc89',
    authDomain: 'resume-builder-7dc89.firebaseapp.com',
    storageBucket: 'resume-builder-7dc89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbbj5KKd69BJXSMH10lOrKNWmxZJjcn0',
    appId: '1:510454324226:android:ee23a368e3fe9a46fddb1b',
    messagingSenderId: '510454324226',
    projectId: 'resume-builder-7dc89',
    storageBucket: 'resume-builder-7dc89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKP-vHg4r0UpO4ef2tJEUhcddtJmxJsM',
    appId: '1:510454324226:ios:d3b005a621802489fddb1b',
    messagingSenderId: '510454324226',
    projectId: 'resume-builder-7dc89',
    storageBucket: 'resume-builder-7dc89.appspot.com',
    iosBundleId: 'com.example.resumeBuilder',
  );
}
